# Generated by Django 5.1.6 on 2025-04-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_populate_test_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingequipment',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='equipment',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='room',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
