# Generated by Django 5.1.6 on 2025-04-03 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_bookingequipment_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='rooms',
        ),
        migrations.AddField(
            model_name='equipment',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipment', to='home.room'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Unique identifier for this physical equipment', max_length=100, null=True),
        ),
    ]
