# Generated by Django 5.1.6 on 2025-04-07 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganization',
            name='level',
            field=models.IntegerField(choices=[(1, 'Member'), (3, 'Leader')], default=1),
        ),
    ]
